@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="page-heading dashboard-heading"><div><span class="eyebrow">ONE OPTICS · WORKSPACE</span><h1>Your clinic, in focus.</h1><p>Welcome back, {{ auth()->user()->name }}. Here’s your business today.</p></div><a class="btn btn-primary" href="{{ route('orders.create') }}"><x-icon name="plus" :size="18"/> New customer order</a></div>
<div class="stats-grid">
<a class="stat-panel" href="{{ route('orders') }}"><div class="stat-top"><span>Active orders</span><span class="stat-icon blue"><x-icon name="bag"/></span></div><strong>{{ $orderCount }}</strong><div class="stat-foot"><small>Awaiting fulfillment</small><x-icon name="arrow" :size="16"/></div></a>
<a class="stat-panel" href="{{ route('payments') }}"><div class="stat-top"><span>Recorded collections</span><span class="stat-icon green"><x-icon name="wallet"/></span></div><strong>{{ \App\Support\Money::format($collections) }}</strong><div class="stat-foot"><small>All recorded payments</small><x-icon name="arrow" :size="16"/></div></a>
<a class="stat-panel" href="{{ route('billing') }}"><div class="stat-top"><span>Outstanding balance</span><span class="stat-icon amber"><x-icon name="bill"/></span></div><strong>{{ \App\Support\Money::format($receivable) }}</strong><div class="stat-foot"><small>Across active bills</small><x-icon name="arrow" :size="16"/></div></a>
<a class="stat-panel" href="{{ route('stock',['low'=>1]) }}"><div class="stat-top"><span>Low-stock products</span><span class="stat-icon rose"><x-icon name="box"/></span></div><strong>{{ $lowStock }} <em>{{ $lowStock===1?'product':'products' }}</em></strong><div class="stat-foot"><small>Ready for replenishment</small><x-icon name="arrow" :size="16"/></div></a>
</div>
<div class="dashboard-analytics"><section class="panel collection-panel"><div class="section-heading compact"><div><h2>Collections overview</h2><p class="section-description">Recorded payments over the last 7 days</p></div><span class="subtle-tag"><x-icon name="clock" :size="14"/> Last 7 days</span></div><div class="chart-total">{{ \App\Support\Money::format($weeklyCollections->sum('amount')) }}<small>Net recorded collections</small></div>@php($chartMax=max(1,$weeklyCollections->max('amount')))<div class="collection-chart" role="img" aria-label="Daily recorded collections for the past seven days"><div class="chart-grid"><span></span><span></span><span></span></div>@foreach($weeklyCollections as $day)<div class="chart-column"><span class="bar-value">{{ $day['amount'] ? \App\Support\Money::format($day['amount']) : '—' }}</span><div class="chart-track"><div class="chart-bar {{ $loop->last?'today':'' }}" style="height:{{ $day['amount'] ? max(4,round($day['amount']/$chartMax*100)) : 0 }}%" title="{{ $day['date'] }}: {{ \App\Support\Money::format($day['amount']) }}"></div></div><span class="bar-day">{{ $day['day'] }}</span></div>@endforeach</div><div class="chart-caption"><span><i></i> Recorded collections</span><a href="{{ route('payments') }}">View payments <x-icon name="arrow" :size="14"/></a></div></section>
<section class="panel fulfillment-panel"><div class="section-heading compact"><h2>Order fulfillment</h2><x-icon name="bag"/></div><p class="section-description">Follow every order from preparation to handover.</p>@foreach(['Pending'=>'Awaiting review','Processing'=>'Being prepared','Ready for Pickup'=>'Ready for pickup','Ready for Delivery'=>'Ready for delivery','Out for Delivery'=>'With the courier'] as $stage=>$label)<a class="stage-row" href="{{ route('orders',['status'=>$stage]) }}"><span class="stage-dot stage-{{ \Illuminate\Support\Str::slug($stage) }}"></span><span>{{ $label }}</span><strong>{{ $orderStages[$stage]??0 }}</strong><x-icon name="arrow" :size="14"/></a>@endforeach<div class="fulfillment-note"><x-icon name="check" :size="18"/><span>{{ $orderStages['Completed']??0 }} {{ ($orderStages['Completed']??0)==1?'order':'orders' }} completed</span></div></section></div>
<div class="dashboard-detail"><section class="panel"><div class="section-heading compact"><div><h2>Recent customer orders</h2><p class="section-description">Your latest orders, all in one place</p></div><a href="{{ route('orders') }}">View all <x-icon name="arrow" :size="16"/></a></div><div class="table-responsive"><table class="table"><thead><tr><th>Order / customer</th><th>Fulfillment</th><th>Status</th><th class="text-end">Total</th></tr></thead><tbody>@forelse($recent as $o)<tr><td><div class="customer-cell"><span class="table-avatar">{{ mb_substr($o->customer->name,0,1) }}</span><div><a href="{{ route('orders.show',$o) }}">{{ $o->number }}</a><small class="d-block">{{ $o->customer->name }}</small></div></div></td><td><span class="fulfillment-type"><x-icon :name="$o->fulfillment==='Pickup'?'building':'delivery'" :size="16"/>{{ $o->fulfillment }}</span></td><td><x-status :value="$o->status"/></td><td class="text-end amount-cell">{{ \App\Support\Money::format($o->total_cents) }}</td></tr>@empty<tr><td colspan="4" class="empty-state">Your first customer order will appear here.</td></tr>@endforelse</tbody></table></div></section>
<aside class="dashboard-rail"><section class="panel"><div class="section-heading compact"><h2>Recent payments</h2><x-icon name="wallet"/></div>@forelse($recentPayments as $p)<a class="recent-payment" href="{{ route('billing.show',$p->billing) }}"><span class="payment-icon"><x-icon name="wallet" :size="17"/></span><span><strong>{{ $p->billing->order->customer->name }}</strong><small>{{ $p->number }} · {{ $p->method }}</small></span><b>{{ \App\Support\Money::format($p->amount_cents) }}<small>{{ $p->status }}</small></b></a>@empty<p class="text-muted">Recorded payments will appear here.</p>@endforelse<a class="panel-bottom-link" href="{{ route('payments') }}">All payment records <x-icon name="arrow" :size="16"/></a></section><section class="replenish-card"><span class="replenish-icon"><x-icon name="glasses" :size="30"/></span><span class="eyebrow">KEEP YOUR COLLECTION READY</span><h3>The right frames.<br>Always in stock.</h3><p>{{ $lowStock }} {{ $lowStock===1?'product is':'products are' }} at or below the reorder level.</p><a href="{{ route('stock',['low'=>1]) }}">Review stock <x-icon name="arrow" :size="17"/></a></section></aside></div>
@if(auth()->user()->role==='Admin')<section class="panel mt-4"><div class="section-heading compact"><div><h2>Purchasing follow-up</h2><p class="section-description">Replenishment that needs your attention</p></div><a href="{{ route('purchases') }}">All purchases <x-icon name="arrow" :size="16"/></a></div><div class="row g-3">@forelse($purchases as $p)<div class="col-md-6 col-xl-4"><a class="purchase-mini" href="{{ route('purchases.show',$p) }}"><span class="mini-icon"><x-icon name="purchase"/></span><span><strong>{{ $p->number }}</strong><small>{{ $p->supplier->name }}</small></span><x-status :value="$p->status"/></a></div>@empty<div class="col-12"><p class="text-muted mb-0">You’re all caught up. No purchases waiting for action.</p></div>@endforelse</div></section>@endif
<div class="workspace-footer"><span>SmartBiz Hub · One Optics Clinic</span><span>Clear vision. Better tomorrow.</span></div>
@endsection