@extends('layouts.app')
@section('title','Stock Management')
@section('content')
<div class="page-heading"><div><span class="eyebrow">EVERY FRAME, ACCOUNTED FOR</span><h1>Stock Management</h1><p>A clear view of what’s on hand, reserved, and ready to sell.</p></div><a class="btn btn-outline-dark" href="{{ route('stock',['low'=>1]) }}"><x-icon name="box"/> Low-stock products</a></div>
<div class="inventory-explainer"><div><span class="mini-icon"><x-icon name="box"/></span><span><strong>On hand</strong><small>Physical stock in your clinic</small></span></div><b>−</b><div><span class="mini-icon"><x-icon name="bag"/></span><span><strong>Reserved</strong><small>Allocated to active orders</small></span></div><b>=</b><div><span class="mini-icon green"><x-icon name="check"/></span><span><strong>Available</strong><small>Ready for a new customer</small></span></div></div>
<div class="panel"><div class="section-heading compact"><h2>Eyewear inventory <span class="count-pill">{{ $products->total() }}</span></h2>@if(auth()->user()->role==='Admin')<a href="{{ route('purchases.create') }}">Create purchase order <x-icon name="arrow" :size="16"/></a>@endif</div><form class="filter-bar"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search eyewear by name…" aria-label="Search product"><button class="btn btn-outline-dark">Search</button><a href="{{ route('stock') }}">Show all</a></form><div class="table-responsive"><table class="table"><thead><tr><th>Product</th><th>Stock in</th><th>Stock out</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Reorder at</th><th>Status</th></tr></thead><tbody>
@forelse($products as $p)<tr><td><div class="table-product"><img src="{{ asset($p->image ?: 'assets/frames-1.svg') }}" alt=""><div><strong>{{ $p->name }}</strong><small class="d-block">{{ $p->code }}</small></div></div></td><td>{{ $p->stock?->quantity_in ?? 0 }}</td><td>{{ $p->stock?->quantity_out ?? 0 }}</td><td>{{ $p->stock?->on_hand ?? 0 }}</td><td>{{ $p->stock?->reserved ?? 0 }}</td><td><strong class="stock-quantity">{{ $p->available }}</strong></td><td>{{ $p->reorder_level }}</td><td><x-status :value="$p->available<=0?'Out of Stock':($p->available<=$p->reorder_level?'Low Stock':'In Stock')"/></td></tr>
<tr class="adjust-row"><td colspan="8"><details><summary>Stock details{{ auth()->user()->role==='Admin'?' & adjustment':'' }} · {{ $p->code }}</summary><div class="stock-details"><span>Last stock in<strong>{{ $p->stock?->last_stock_in?->format('M d, Y · h:i A') ?: 'No stock received' }}</strong></span><span>Last stock out<strong>{{ $p->stock?->last_stock_out?->format('M d, Y · h:i A') ?: 'No stock released' }}</strong></span><span>Updated by<strong>{{ $p->stock?->updatedBy?->name ?: '—' }}</strong></span></div><p class="small text-muted mb-3">{{ $p->stock?->remarks ?: 'No stock remarks.' }}</p>@if(auth()->user()->role==='Admin')<form method="POST" action="{{ route('stock.adjust',$p) }}" class="d-flex flex-wrap gap-2" data-confirm="Record this inventory adjustment?">@csrf<input class="form-control quantity" type="number" name="quantity" placeholder="+/− qty" aria-label="Stock adjustment quantity" min="-10000" max="10000" required><input class="form-control reason-input" name="reason" placeholder="Reason for adjustment" aria-label="Adjustment reason" minlength="5" required><button class="btn btn-outline-dark">Save adjustment</button></form>@endif</details></td></tr>
@empty<tr><td colspan="8" class="empty-state"><x-icon name="box" :size="32"/><h3>No inventory found</h3><p>Try another search or add your first product.</p></td></tr>@endforelse
</tbody></table></div>{{ $products->links() }}</div><div class="inline-note"><x-icon name="shield"/><p>Receiving a purchase adds stock. Completing a customer order deducts stock. Reservations prevent the same item from being promised twice.</p></div>
@endsection