<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','SmartBiz Hub') · One Optics Clinic</title><link rel="icon" href="{{ asset('assets/mark.svg') }}" type="image/svg+xml"><link rel="stylesheet" href="{{ asset('assets/bootstrap.min.css') }}"><link rel="stylesheet" href="{{ asset('assets/app.css') . '?v=4' }}"><link rel="stylesheet" href="{{ asset('assets/design.css') }}?v=2"></head>
@php($management=request()->is('manage*'))
<body class="{{ $management ? 'management' : 'storefront' }}">
@if($management)
<aside class="sidebar" id="sidebar"><a class="brand sidebar-brand" href="{{ route('dashboard') }}"><img src="{{ asset('assets/mark.svg') }}" alt=""><span>SmartBiz Hub<small>ONE OPTICS CLINIC</small></span></a><div class="nav-caption">{{ auth()->user()->role }} WORKSPACE</div><nav>
@php($nav=[['Dashboard','dashboard',null,'grid'],['Customers','records','customers','users'],['Products','records','products','glasses']])
@if(auth()->user()->role==='Admin') @php($nav=array_merge($nav,[['Suppliers','records','suppliers','building'],['Purchase Orders','purchases',null,'purchase']])) @endif
@php($nav=array_merge($nav,[['Stock Management','stock',null,'box'],['Customer Orders','orders',null,'bag'],['Billing','billing',null,'bill'],['Payments','payments',null,'wallet']]))
@if(auth()->user()->role==='Admin') @php($nav=array_merge($nav,[['Reports','reports',null,'chart'],['User Management','records','users','shield'],['Settings','settings',null,'settings']])) @endif
@foreach($nav as [$label,$route,$param,$icon])
@php($active=$param ? request()->route('resource')===$param : request()->routeIs($route,$route.'.*'))
<a href="{{ route($route,$param ? [$param] : []) }}" class="{{ $active?'active':'' }}"><span class="nav-symbol"><x-icon :name="$icon"/></span>{{ $label }}</a>
@endforeach
</nav><div class="sidebar-bottom"><form action="{{ route('logout') }}" method="POST">@csrf<button class="logout">↪ Log out</button></form></div></aside>
<div class="workspace"><header class="topbar"><button type="button" class="menu-toggle" aria-label="Toggle navigation" onclick="document.getElementById('sidebar').classList.toggle('open')">☰</button><div class="breadcrumb-label">One Optics Clinic <span>/</span> @yield('title','Dashboard')</div><div class="topbar-right"><span class="workspace-date">{{ now()->format('D, d M Y') }}</span><span class="demo-indicator"><i></i> Prototype</span><div class="user-summary"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><span>{{ auth()->user()->name }}<small>{{ auth()->user()->role }}</small></span></div></div></header><main class="workspace-main">
@else
<div class="announcement">Clear vision. Better tomorrow. <span>Visit our Manila clinic · Pickup & delivery available</span></div>
<header class="store-nav container"><a class="brand" href="{{ route('home') }}"><img src="{{ asset('assets/mark.svg') }}" alt=""><span>SmartBiz Hub<small>ONE OPTICS CLINIC</small></span></a>
<form class="header-search" method="GET" action="{{ route('catalog') }}" role="search"><label class="visually-hidden" for="store-search">Search products</label><input id="store-search" name="search" type="search" placeholder="Find your next pair…" value="{{ request('search') }}"><button aria-label="Search products"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg></button></form>
<div class="store-actions"><a class="bag-link" href="{{ route('cart') }}"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M2 3h3l3 13h11l3-10H6"/><circle cx="9" cy="21" r="1"/><circle cx="19" cy="21" r="1"/></svg> Cart <span>{{ array_sum(session('cart',[])) }}</span></a>
@auth<details class="account-menu"><summary><x-icon name="users"/> Account <span aria-hidden="true">⌄</span></summary><div class="account-dropdown"><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->role }}</small>@if(auth()->user()->role==='Customer')<a href="{{ route('account') }}">My account & orders</a>@else<a href="{{ route('dashboard') }}">Open {{ auth()->user()->role }} dashboard</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button>Log out</button></form></div></details>@else<a class="btn btn-primary btn-sm" href="{{ route('login') }}">Login</a><a class="register-link" href="{{ route('register') }}">Register</a>@endauth</div></header>
<nav class="shop-category-nav" aria-label="Shop categories"><div class="container">@foreach(['All products'=>null,'Eyeglasses'=>'Eyeglass Frame','Contact Lenses & Solution'=>'Contact Lenses & Solution','Reading Glasses'=>'Reading Glasses','Accessories'=>'Accessory'] as $label=>$category)<a class="{{ request()->routeIs('catalog') && request('category')===$category ? 'active' : '' }}" href="{{ route('catalog',$category ? ['category'=>$category] : []) }}">{{ $label }}</a>@endforeach<a class="{{ request()->routeIs('info') ? 'active' : '' }}" href="{{ route('info','about') }}">Our Clinic & Location</a></div></nav><main class="store-main">
@endif
<div class="{{ $management?'':'container' }}">@if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please check the following:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif</div>
@yield('content')
</main>@if($management)</div>@else<footer class="store-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="{{ route('home') }}"><img src="{{ asset('assets/mark.svg') }}" alt=""><span>SmartBiz Hub<small>ONE OPTICS CLINIC</small></span></a><p>Thoughtful eyewear.<br>A clearer everyday.</p></div><div><h3>Explore</h3><a href="{{ route('catalog') }}">Shop eyewear</a><a href="{{ route('info','about') }}">Our clinic & location</a></div><div><h3>Your account</h3><a href="{{ route('account') }}">Orders & billing</a><a href="{{ route('register') }}">Create an account</a><a href="{{ route('login') }}">Admin & Staff sign in</a></div><div><h3>Visit One Optics Clinic</h3><p>{{ $clinic['address'] ?? '' }}</p><span>Pickup and delivery available</span></div></div><div class="footer-bottom">© {{ date('Y') }} SmartBiz Hub · One Optics Clinic. All rights reserved.</div></div></footer>@endif
<script src="{{ asset('assets/bootstrap.bundle.min.js') }}"></script><script src="{{ asset('assets/app.js') }}"></script>@stack('scripts')
</body></html>
