@extends('layouts.app')
@section('title',$order->number)
@section('content')
<div class="{{ $public?'container section-space':'' }}"><div class="page-heading"><div><a href="{{ $public?route('account'):route('orders') }}">← {{ $public?'My account':'Customer orders' }}</a><h1 class="mt-2">{{ $order->number }}</h1><p>{{ $order->created_at->format('F d, Y · h:i A') }} · {{ $order->type }} · {{ $order->fulfillment }}</p><x-status :value="$order->status"/></div><div class="d-flex flex-wrap gap-2">@if(!$public) @php($actions=match($order->status){'Pending'=>['process'=>'Start processing'],'Processing'=>['ready'=>$order->fulfillment==='Pickup'?'Ready for pickup':'Ready for delivery'],'Ready for Pickup','Out for Delivery'=>['complete'=>'Complete order'],default=>[]}) @foreach($actions as $action=>$label)<form action="{{ route('orders.status',$order) }}" method="POST" data-confirm="{{ $label }}?">@csrf<input type="hidden" name="action" value="{{ $action }}"><button class="btn btn-primary">{{ $label }}</button></form>@endforeach @endif
@if(($public && $order->status==='Pending') || (!$public && in_array($order->status,['Pending','Processing'])))<form action="{{ $public?route('my.cancel',$order):route('orders.status',$order) }}" method="POST" data-confirm="Cancel this order and release the reserved stock?">@csrf<input type="hidden" name="action" value="cancel"><button class="btn btn-outline-danger">Cancel order</button></form>@endif</div></div>
<x-order-update :order="$order"/>
<div class="row g-4"><div class="col-lg-8"><div class="panel"><h2>Eyewear in this order</h2><div class="table-responsive"><table class="table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }}<small class="d-block text-muted">{{ $item->product->code }}</small></td><td>{{ $item->quantity }}</td><td>{{ \App\Support\Money::format($item->unit_price_cents) }}</td><td>{{ \App\Support\Money::format($item->subtotal_cents) }}</td></tr>@endforeach</tbody></table></div><div class="summary-line total"><span>{{ $order->billing?'Billed total':'Order estimate' }}</span><strong>{{ \App\Support\Money::format($order->total_cents) }}</strong></div>@if($order->notes)<p class="mt-3">Notes: {{ $order->notes }}</p>@endif</div>
<div class="panel mt-4"><h2>Billing & payments</h2>@if($order->billing)<div class="summary-line"><a href="{{ route('invoice',$order->billing) }}">{{ $order->billing->number }} · View printable bill ↗</a><x-status :value="$order->billing->status"/></div><div class="summary-line"><span>Amount paid</span><strong>{{ \App\Support\Money::format($order->billing->paid_cents) }}</strong></div><div class="summary-line"><span>Balance</span><strong>{{ \App\Support\Money::format($order->billing->balance_cents) }}</strong></div>@foreach($order->billing->payments as $payment)<div class="summary-line"><a href="{{ route('receipt',$payment) }}">{{ $payment->number }} · {{ $payment->method }}</a><span>{{ \App\Support\Money::format($payment->amount_cents) }} · {{ $payment->status }}</span></div>@endforeach @if(!$public)<a class="btn btn-primary mt-3" href="{{ route('billing.show',$order->billing) }}">Open billing & record payment</a>@endif @else<p class="text-muted">{{ $public?'The clinic will prepare your bill. Check back here for updates.':'Generate a bill before recording payment.' }}</p>@if(!$public && !in_array($order->status,['Cancelled','Completed']))<a class="btn btn-primary" href="{{ route('billing.create',$order) }}">Generate bill</a>@endif @endif</div></div>
<div class="col-lg-4"><div class="panel"><span class="eyebrow">CUSTOMER</span><h2>{{ $order->customer->name }}</h2><p>{{ $order->customer->phone }}<br>{{ $order->customer->email }}</p><hr><h3>{{ $order->fulfillment }} details</h3>@if($order->fulfillment==='Delivery')<p class="small text-muted">Delivery updates are entered by clinic staff. Courier references are provided for your records.</p>@endif<p>{{ $order->fulfillment==='Delivery'?$order->delivery_address:($clinic['address']??'') }}</p>@if($order->pickup_date)<p>Preferred date: {{ $order->pickup_date }}</p>@endif @if($order->courier)<p>Courier: {{ $order->courier }}<br>Courier reference: <strong>{{ $order->tracking_number }}</strong></p>@endif<p class="small text-muted">Handled by: {{ $order->user?->name ?: 'Awaiting staff assignment' }}</p></div>
@if(!$public && $order->status==='Ready for Delivery')<form class="panel mt-4" action="{{ route('orders.status',$order) }}" method="POST">@csrf<input type="hidden" name="action" value="dispatch"><h2>Dispatch delivery</h2><p class="small">Confirm dispatch with the courier, then enter the reference below. Full payment must be recorded before dispatch.</p><label class="form-label">Courier</label><input class="form-control mb-3" name="courier" required><label class="form-label">Courier reference</label><input class="form-control mb-3" name="tracking_number" required><button class="btn btn-primary">Mark out for delivery</button></form>@endif</div></div></div>
@endsection
